Create a KittySay Command
KittyCAD/cli pull request #199
Opened 2023-02-16 16:58 UTC by gserena01

related to #13

2023-02-16 17:00 UTC, gserena01 commented
Strange, but line 14 of src/cmd_kittysay.rs will only run with line 15 present... I'm wondering what might be happening here?

2023-02-16 17:00 UTC, gserena01 commented
Also, @hanbollar if there was an image of KittyCAD without her shadow I think the image would read better as ASCII art.

2023-02-16 17:38 UTC, hanbollar commented
@gserena01 - here's two options

![just_the_kitty_small](https://user-images.githubusercontent.com/19377312/219444477-83e64096-234e-4bf9-af01-7028c56560b9.png)
![just_the_kitty](https://user-images.githubusercontent.com/19377312/219444481-336e599b-671a-4731-8464-11c2491057c1.png)

2023-02-22 23:09 UTC, iterion commented
> Strange, but line 14 of src/cmd_kittysay.rs will only run with line 15 present... I'm wondering what might be happening here?

Sorry, I totally missed this. I assume you're seeing an issue like this:
```
error[E0308]: mismatched types
  --> src/cmd_kittysay.rs:13:14
   |
13 |     async fn run(&self, ctx: &mut crate::context::Context) -> Result<()> {
   |              ^^^
   |              |
   |              expected enum `Result`, found `()`
   |              implicitly returns `()` as its body has no tail or `return` expression
   |
   = note:   expected enum `Result<(), anyhow::Error>`
           found unit type `()`
```

Basically, the return type of the function is the Result type. In particular, we use a convenient wrapper around the std called [anyhow](https://docs.rs/anyhow/latest/anyhow/).

If you only have the line:
```
        writeln!(ctx.io.out, "KITTYSAYSTUFF!");
```
Then the return type of the function is (). Rust has both implicit and explicit returns. If you end a function without a semicolon then the result of that statement is returned. 

To get this compiling without warnings we'd have to change it to:
```
        writeln!(ctx.io.out, "KITTYSAYSTUFF!")?;
        Ok(())
```

The `Ok(())` at the end matches the return type. You'll note the line above added a `?` which is a shortcut for an early return plus converting the error type. Let me know if you're still stuck.

2023-02-22 23:34 UTC, hanbollar commented
@gserena01 - correct me if im wrong, but if `KITTYSAYSTUFF` is just a placeholder, make sure to swap it out with what the actual txt ascii is

overall lgtm, gonna leave it up to adam for final review on this (so no need to request me for review for this pr 👍 ) - removing the request

2023-02-28 18:08 UTC, iterion approved these changes

2023-02-28 18:08 UTC, iterion commented on src/cmd_say.rs
> +            let print_text = format!("{}{}{}", bar, text, bar);
```suggestion
            let print_text = format!("|{}|", text);
```

2023-02-28 18:08 UTC, iterion commented on src/cmd_say.rs
> +            let print_text = format!("{}{}{}", bar, text, bar);
You could remove the line above as well by including the `|` in the format.

2023-02-28 18:08 UTC, iterion commented on src/cmd_say.rs
> +        if self.input.len() > 0 {
Follow the clippy lint.

2023-02-28 18:08 UTC, iterion commented on src/cmd_say.rs
> +///     $ kittycad say
We might want to add more examples here now that you can also give arguments.

2023-02-28 18:08 UTC, iterion commented on src/cmd_say.rs
> +}
We should add at least one test. Check https://github.com/KittyCAD/cli/blob/main/src/cmd_file.rs#L431 and other files for some example test setup.

2023-03-02 19:27 UTC, iterion requested changes
Thanks for adding the tests! This looks good aside from just needing to run cargo fmt and following the clippy lints.

2023-03-02 19:27 UTC, iterion commented on src/cmd_say.rs
> +        if self.input.len() > 0 {
We can reuse `kitty_speaking` here. And above we should use `!self.input.is_empty()` like clippy suggests.

2023-03-02 19:56 UTC, iterion approved these changes
Assuming tests all pass this looks good to me!

2023-03-03 15:07 UTC, merged

2023-03-03 15:07 UTC, gserena01 commented
fixes #13